name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.207.220.76 "
            if [ -d /var/www/html/.git ]; then
              echo 'El repositorio ya existe, ejecutando git pull...'
              cd /var/www/html &&
              git reset --hard &&
              git pull origin main
            else
              echo 'El repositorio no existe, clonando...'
              sudo rm -rf /var/www/html/* &&
              git clone https://github.com/edflorese/basic-react.git /var/www/html
            fi &&
            sudo systemctl restart httpd
          "
