name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 18.207.220.76
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/html
            git clone https://github.com/edflorese/basic-react.git
            cd basic-react
            sudo chown -R ec2-user:ec2-user /var/www/html/basic-react
            npm install
            npm run build
            sudo mv dist/* /var/www/html/
            sudo chown -R apache:apache /var/www/html/
            sudo chmod -R 755 /var/www/html/
            sudo systemctl restart httpd