name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 18.207.220.76
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/my-app || exit

            git reset --hard
            git pull origin master

            sudo yum install -y nodejs npm
            npm install

            # Construye la aplicación
            npm run build

            sudo cp -r build/* /var/www/html/

            sudo systemctl restart httpd
