name: Update EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Update code on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
          sudo yum install -y nodejs npm &&
          sudo chown -R ec2-user:ec2-user /proyectos/basic-react  
          cd /proyectos/basic-react &&
          sudo chown -R ec2-user:ec2-user node_modules/
          git reset --hard HEAD &&
          git pull origin master &&
          npm run build &&
          sudo rm -rf /var/www/html/* &&
          sudo cp -r dist/* /var/www/html/ &&
          sudo systemctl restart httpd
        "